// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetAccountRateLimitsParams = {
/**
 * Whether the server should also make the online request for reset-credit
 * details. Callers that only need the locally cached usage snapshots can
 * disable this to avoid coupling UI hydration to network latency. Defaults
 * to `true` when omitted.
 */
includeResetCredits?: boolean | null, };
