// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetAccountParams = {
/**
 * When `true`, requests a proactive token refresh before returning.
 *
 * Triggers the normal ChatGPT refresh-token flow for pool-managed auth.
 */
refreshToken?: boolean, };
